### ISSUE TITLE
Stop and skip the song != pause and resume

### ISSUE THREAD

**Issue by sudo-apt-get-install** [agubelu/discord-music-bot#5]
The title says it all.

This is one of the first discord bots I've found that worked and I would like you to make it so it actually resumes.

**Comment by agubelu** [comment]
Well, pausing and resuming songs at a certain time instead of skipping it completely will need a few tweaks since I didn't have any plans of doing so when I made the bot. I'll add it to the TODO list to do it when I have some free time from university but of course you are welcome to do a PR if you want to do it yourself.
